#!/usr/bin/env node
// Batch 6: Final push to 700+ tools

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const toolsPath = path.join(__dirname, '../registry/tools.json');
const data = JSON.parse(fs.readFileSync(toolsPath, 'utf8'));

const existingSlugs = new Set(data.tools.map(t => t.slug));

const newTools = [
  // Messaging/Notification
  {
    slug: "ntfy",
    name: "ntfy",
    vendor: { name: "binwiederhier", domain: "ntfy.sh", verified: false },
    repo: "https://github.com/binwiederhier/ntfy",
    docs: "https://docs.ntfy.sh/",
    install: { brew: "ntfy", apt: "ntfy" },
    capabilities: { jsonOutput: true, auth: ["env:NTFY_TOKEN"], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["notifications", "messaging"],
    tier: "community",
    description: "Send push notifications to your phone via PUT/POST with a simple API."
  },
  {
    slug: "gotify-cli",
    name: "Gotify CLI",
    vendor: { name: "gotify", domain: "gotify.net", verified: false },
    repo: "https://github.com/gotify/cli",
    docs: "https://gotify.net/docs/",
    install: {},
    capabilities: { jsonOutput: true, auth: ["config file"], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["notifications", "messaging"],
    tier: "community",
    description: "CLI for pushing to self-hosted Gotify notification server."
  },
  {
    slug: "apprise",
    name: "Apprise",
    vendor: { name: "caronc", domain: "github.com/caronc", verified: false },
    repo: "https://github.com/caronc/apprise",
    docs: "https://github.com/caronc/apprise/wiki",
    install: { pip: "apprise" },
    capabilities: { jsonOutput: false, auth: ["various"], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["notifications", "messaging", "multi-platform"],
    tier: "community",
    description: "Push notifications to 90+ services with a single API call."
  },
  // More search/grep tools
  {
    slug: "ag",
    name: "The Silver Searcher",
    vendor: { name: "ggreer", domain: "geoff.greer.fm/ag", verified: false },
    repo: "https://github.com/ggreer/the_silver_searcher",
    docs: "https://github.com/ggreer/the_silver_searcher#readme",
    install: { brew: "the_silver_searcher", apt: "silversearcher-ag" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["search", "grep"],
    tier: "community",
    description: "Code-searching tool similar to ack, but faster."
  },
  {
    slug: "ack",
    name: "ack",
    vendor: { name: "Andy Lester", domain: "beyondgrep.com", verified: false },
    repo: "https://github.com/beyondgrep/ack3",
    docs: "https://beyondgrep.com/documentation/",
    install: { brew: "ack", apt: "ack" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["search", "grep"],
    tier: "community",
    description: "Search tool like grep, optimized for programmers."
  },
  {
    slug: "ugrep",
    name: "ugrep",
    vendor: { name: "Genivia", domain: "ugrep.com", verified: false },
    repo: "https://github.com/Genivia/ugrep",
    docs: "https://ugrep.com/",
    install: { brew: "ugrep", apt: "ugrep" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 4, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["search", "grep"],
    tier: "community",
    description: "Ultra fast grep with interactive query TUI and hexdumps."
  },
  // Backup tools
  {
    slug: "borg",
    name: "BorgBackup",
    vendor: { name: "borgbackup", domain: "borgbackup.org", verified: false },
    repo: "https://github.com/borgbackup/borg",
    docs: "https://borgbackup.readthedocs.io/",
    install: { brew: "borgbackup", apt: "borgbackup" },
    capabilities: { jsonOutput: true, auth: ["env:BORG_PASSPHRASE"], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["backup", "encryption"],
    tier: "community",
    description: "Deduplicating archiver with compression and encryption."
  },
  {
    slug: "kopia",
    name: "Kopia",
    vendor: { name: "kopia", domain: "kopia.io", verified: false },
    repo: "https://github.com/kopia/kopia",
    docs: "https://kopia.io/docs/",
    install: { brew: "kopia" },
    capabilities: { jsonOutput: true, auth: ["env:KOPIA_PASSWORD"], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["backup", "encryption"],
    tier: "community",
    description: "Cross-platform backup tool with fast incremental backups."
  },
  {
    slug: "duplicacy",
    name: "Duplicacy",
    vendor: { name: "gilbertchen", domain: "duplicacy.com", verified: false },
    repo: "https://github.com/gilbertchen/duplicacy",
    docs: "https://duplicacy.com/",
    install: { brew: "duplicacy" },
    capabilities: { jsonOutput: true, auth: ["various"], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["backup", "cloud"],
    tier: "community",
    description: "Cloud backup tool with lock-free deduplication."
  },
  // SSH tools
  {
    slug: "ssh",
    name: "OpenSSH",
    vendor: { name: "OpenSSH", domain: "openssh.com", verified: true },
    repo: "https://github.com/openssh/openssh-portable",
    docs: "https://www.openssh.com/manual.html",
    install: { apt: "openssh-client" },
    capabilities: { jsonOutput: false, auth: ["ssh keys", "password"], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 4, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["ssh", "networking", "security"],
    tier: "verified",
    description: "OpenSSH remote login client."
  },
  {
    slug: "sshpass",
    name: "sshpass",
    vendor: { name: "Shachar Shemesh", domain: "sourceforge.net/projects/sshpass", verified: false },
    repo: "https://github.com/kevinburke/sshpass",
    docs: "https://linux.die.net/man/1/sshpass",
    install: { brew: "hudochenkov/sshpass/sshpass", apt: "sshpass" },
    capabilities: { jsonOutput: false, auth: ["password"], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 2, pipelineFriendly: 5 },
    agentScore: 7,
    categories: ["ssh", "automation"],
    tier: "community",
    description: "Non-interactive SSH password provider."
  },
  {
    slug: "mosh",
    name: "Mosh",
    vendor: { name: "mosh", domain: "mosh.org", verified: false },
    repo: "https://github.com/mobile-shell/mosh",
    docs: "https://mosh.org/#usage",
    install: { brew: "mosh", apt: "mosh" },
    capabilities: { jsonOutput: false, auth: ["ssh keys"], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 3, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 3 },
    agentScore: 7,
    categories: ["ssh", "mobile", "networking"],
    tier: "community",
    description: "Mobile shell for roaming and intermittent connectivity."
  },
  {
    slug: "sshfs",
    name: "SSHFS",
    vendor: { name: "libfuse", domain: "github.com/libfuse", verified: false },
    repo: "https://github.com/libfuse/sshfs",
    docs: "https://github.com/libfuse/sshfs#readme",
    install: { brew: "sshfs", apt: "sshfs" },
    capabilities: { jsonOutput: false, auth: ["ssh keys"], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["ssh", "filesystem", "mount"],
    tier: "community",
    description: "Mount remote filesystems over SSH."
  },
  // Task runners/Build tools
  {
    slug: "make",
    name: "GNU Make",
    vendor: { name: "GNU", domain: "gnu.org", verified: true },
    repo: "https://github.com/mirror/make",
    docs: "https://www.gnu.org/software/make/manual/",
    install: { brew: "make", apt: "make" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["build", "automation"],
    tier: "verified",
    description: "Build automation tool that builds targets from dependencies."
  },
  {
    slug: "ninja",
    name: "Ninja",
    vendor: { name: "ninja-build", domain: "ninja-build.org", verified: false },
    repo: "https://github.com/ninja-build/ninja",
    docs: "https://ninja-build.org/manual.html",
    install: { brew: "ninja", apt: "ninja-build" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["build", "compilation"],
    tier: "community",
    description: "Small build system with a focus on speed."
  },
  {
    slug: "cmake",
    name: "CMake",
    vendor: { name: "Kitware", domain: "cmake.org", verified: true },
    repo: "https://github.com/Kitware/CMake",
    docs: "https://cmake.org/documentation/",
    install: { brew: "cmake", apt: "cmake" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 4, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["build", "cross-platform"],
    tier: "verified",
    description: "Cross-platform build system generator."
  },
  {
    slug: "bazel",
    name: "Bazel",
    vendor: { name: "Google", domain: "bazel.build", verified: true },
    repo: "https://github.com/bazelbuild/bazel",
    docs: "https://bazel.build/docs",
    install: { brew: "bazel" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 3, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["build", "monorepo"],
    tier: "verified",
    description: "Fast, scalable, multi-language build system."
  },
  {
    slug: "buck2",
    name: "Buck2",
    vendor: { name: "Meta", domain: "buck2.build", verified: true },
    repo: "https://github.com/facebook/buck2",
    docs: "https://buck2.build/docs/",
    install: {},
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["build", "monorepo"],
    tier: "verified",
    description: "Fast, reliable, and extensible build system by Meta."
  },
  {
    slug: "pants",
    name: "Pants",
    vendor: { name: "Pants Build", domain: "pantsbuild.org", verified: false },
    repo: "https://github.com/pantsbuild/pants",
    docs: "https://www.pantsbuild.org/docs",
    install: {},
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["build", "monorepo", "python"],
    tier: "community",
    description: "Fast, scalable, user-friendly build system for monorepos."
  },
  // Clipboard tools
  {
    slug: "xclip",
    name: "xclip",
    vendor: { name: "astrand", domain: "github.com/astrand", verified: false },
    repo: "https://github.com/astrand/xclip",
    docs: "https://github.com/astrand/xclip#readme",
    install: { apt: "xclip" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["clipboard", "x11"],
    tier: "community",
    description: "Command line interface to X11 clipboard."
  },
  {
    slug: "xsel",
    name: "xsel",
    vendor: { name: "kfish", domain: "github.com/kfish", verified: false },
    repo: "https://github.com/kfish/xsel",
    docs: "https://github.com/kfish/xsel#readme",
    install: { apt: "xsel" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["clipboard", "x11"],
    tier: "community",
    description: "Manipulate X selection (clipboard) from command line."
  },
  {
    slug: "pbcopy",
    name: "pbcopy",
    vendor: { name: "Apple", domain: "apple.com", verified: true },
    repo: null,
    docs: "https://ss64.com/osx/pbcopy.html",
    install: {},
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["clipboard", "macos"],
    tier: "verified",
    description: "macOS utility to copy data to the clipboard."
  },
  // Process managers
  {
    slug: "pm2",
    name: "PM2",
    vendor: { name: "Keymetrics", domain: "pm2.io", verified: false },
    repo: "https://github.com/Unitech/pm2",
    docs: "https://pm2.keymetrics.io/docs/",
    install: { npm: "pm2" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["process-manager", "nodejs"],
    tier: "community",
    description: "Production process manager for Node.js with clustering."
  },
  {
    slug: "supervisor",
    name: "Supervisor",
    vendor: { name: "Supervisor", domain: "supervisord.org", verified: false },
    repo: "https://github.com/Supervisor/supervisor",
    docs: "http://supervisord.org/",
    install: { pip: "supervisor", apt: "supervisor" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["process-manager", "daemon"],
    tier: "community",
    description: "Process control system for UNIX."
  },
  {
    slug: "systemctl",
    name: "systemctl",
    vendor: { name: "systemd", domain: "systemd.io", verified: true },
    repo: "https://github.com/systemd/systemd",
    docs: "https://www.freedesktop.org/software/systemd/man/systemctl.html",
    install: { apt: "systemd" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["systemd", "services", "linux"],
    tier: "verified",
    description: "Control the systemd system and service manager."
  },
  {
    slug: "journalctl",
    name: "journalctl",
    vendor: { name: "systemd", domain: "systemd.io", verified: true },
    repo: "https://github.com/systemd/systemd",
    docs: "https://www.freedesktop.org/software/systemd/man/journalctl.html",
    install: { apt: "systemd" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["systemd", "logging", "linux"],
    tier: "verified",
    description: "Query the systemd journal logs."
  },
  // More database tools
  {
    slug: "clickhouse-client",
    name: "ClickHouse Client",
    vendor: { name: "ClickHouse", domain: "clickhouse.com", verified: true },
    repo: "https://github.com/ClickHouse/ClickHouse",
    docs: "https://clickhouse.com/docs/en/interfaces/cli",
    install: { brew: "clickhouse" },
    capabilities: { jsonOutput: true, auth: ["connection string"], idempotent: false, interactive: true, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 4, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["database", "clickhouse", "analytics"],
    tier: "verified",
    description: "Native CLI client for ClickHouse analytics database."
  },
  {
    slug: "cqlsh",
    name: "cqlsh",
    vendor: { name: "Apache", domain: "cassandra.apache.org", verified: true },
    repo: "https://github.com/apache/cassandra",
    docs: "https://cassandra.apache.org/doc/latest/cassandra/tools/cqlsh.html",
    install: { pip: "cqlsh" },
    capabilities: { jsonOutput: false, auth: ["connection string"], idempotent: false, interactive: true, streaming: true },
    agentScores: { jsonOutput: 3, nonInteractive: 4, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["database", "cassandra", "nosql"],
    tier: "verified",
    description: "CQL Shell for Apache Cassandra database."
  },
  {
    slug: "duckdb",
    name: "DuckDB CLI",
    vendor: { name: "DuckDB", domain: "duckdb.org", verified: false },
    repo: "https://github.com/duckdb/duckdb",
    docs: "https://duckdb.org/docs/api/cli",
    install: { brew: "duckdb" },
    capabilities: { jsonOutput: true, auth: [], idempotent: false, interactive: true, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 4, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["database", "analytics", "sql"],
    tier: "community",
    description: "In-process SQL OLAP database for analytics."
  },
  // Schema/API tools
  {
    slug: "openapi-generator",
    name: "OpenAPI Generator",
    vendor: { name: "OpenAPI Tools", domain: "openapi-generator.tech", verified: false },
    repo: "https://github.com/OpenAPITools/openapi-generator",
    docs: "https://openapi-generator.tech/docs/",
    install: { brew: "openapi-generator", npm: "@openapitools/openapi-generator-cli" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["api", "codegen", "openapi"],
    tier: "community",
    description: "Generate clients, servers, and docs from OpenAPI specs."
  },
  {
    slug: "spectral",
    name: "Spectral",
    vendor: { name: "Stoplight", domain: "stoplight.io", verified: true },
    repo: "https://github.com/stoplightio/spectral",
    docs: "https://docs.stoplight.io/docs/spectral/",
    install: { npm: "@stoplight/spectral-cli" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["api", "linting", "openapi"],
    tier: "verified",
    description: "JSON/YAML linter with OpenAPI and AsyncAPI support."
  },
  {
    slug: "buf",
    name: "buf",
    vendor: { name: "Buf", domain: "buf.build", verified: true },
    repo: "https://github.com/bufbuild/buf",
    docs: "https://buf.build/docs/",
    install: { brew: "bufbuild/buf/buf" },
    capabilities: { jsonOutput: true, auth: ["buf.yaml"], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["protobuf", "grpc", "api"],
    tier: "verified",
    description: "Protobuf tooling - lint, format, breaking changes detection."
  },
  // Time/Date tools
  {
    slug: "dateutils",
    name: "dateutils",
    vendor: { name: "hroptatyr", domain: "github.com/hroptatyr", verified: false },
    repo: "https://github.com/hroptatyr/dateutils",
    docs: "https://github.com/hroptatyr/dateutils#readme",
    install: { brew: "dateutils", apt: "dateutils" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["datetime", "conversion"],
    tier: "community",
    description: "Command line date and time utilities."
  },
  // Cron/Scheduling
  {
    slug: "fcron",
    name: "fcron",
    vendor: { name: "fcron", domain: "fcron.free.fr", verified: false },
    repo: "https://github.com/yo8192/fcron",
    docs: "http://fcron.free.fr/doc/en/fcron.8.html",
    install: { apt: "fcron" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["cron", "scheduling"],
    tier: "community",
    description: "Feature-rich cron daemon for systems not always up."
  },
  // DNS tools
  {
    slug: "drill",
    name: "drill",
    vendor: { name: "NLnet Labs", domain: "nlnetlabs.nl", verified: true },
    repo: "https://github.com/NLnetLabs/ldns",
    docs: "https://nlnetlabs.nl/documentation/ldns/",
    install: { brew: "ldns", apt: "ldnsutils" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 4 },
    agentScore: 9,
    categories: ["dns", "dnssec"],
    tier: "verified",
    description: "DNS lookup tool with DNSSEC support."
  },
  {
    slug: "dnsx",
    name: "dnsx",
    vendor: { name: "ProjectDiscovery", domain: "projectdiscovery.io", verified: false },
    repo: "https://github.com/projectdiscovery/dnsx",
    docs: "https://github.com/projectdiscovery/dnsx#readme",
    install: { go: "github.com/projectdiscovery/dnsx/cmd/dnsx" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["dns", "security", "recon"],
    tier: "community",
    description: "Fast and multi-purpose DNS toolkit."
  },
  // Markdown tools
  {
    slug: "mdx",
    name: "mdx",
    vendor: { name: "mdx-js", domain: "mdxjs.com", verified: false },
    repo: "https://github.com/mdx-js/mdx",
    docs: "https://mdxjs.com/docs/",
    install: { npm: "@mdx-js/mdx" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["markdown", "jsx", "documentation"],
    tier: "community",
    description: "Markdown for the component era - JSX in Markdown."
  },
  {
    slug: "markdownlint",
    name: "markdownlint",
    vendor: { name: "David Anson", domain: "github.com/DavidAnson", verified: false },
    repo: "https://github.com/DavidAnson/markdownlint",
    docs: "https://github.com/DavidAnson/markdownlint#readme",
    install: { npm: "markdownlint-cli" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["markdown", "linting"],
    tier: "community",
    description: "Node.js style checker and lint tool for Markdown."
  },
  // More utilities
  {
    slug: "renameutils",
    name: "renameutils",
    vendor: { name: "Ola Lundqvist", domain: "github.com/olaLundworst", verified: false },
    repo: "https://github.com/olaLundworst/renameutils",
    docs: "https://www.nongnu.org/renameutils/",
    install: { brew: "renameutils", apt: "renameutils" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: true, streaming: false },
    agentScores: { jsonOutput: 1, nonInteractive: 3, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 3 },
    agentScore: 6,
    categories: ["files", "rename"],
    tier: "community",
    description: "Rename files faster with editor-based bulk renaming."
  },
  {
    slug: "mmv",
    name: "mmv",
    vendor: { name: "Vladimir Lanin", domain: "sourceforge.net/projects/mmv", verified: false },
    repo: "https://github.com/itchyny/mmv",
    docs: "https://github.com/itchyny/mmv#readme",
    install: { brew: "mmv", go: "github.com/itchyny/mmv/cmd/mmv" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["files", "rename", "batch"],
    tier: "community",
    description: "Rename multiple files with editor."
  },
  {
    slug: "vidir",
    name: "vidir",
    vendor: { name: "Joey Hess", domain: "joeyh.name", verified: false },
    repo: "https://github.com/trapd00r/vidir",
    docs: "https://linux.die.net/man/1/vidir",
    install: { brew: "moreutils", apt: "moreutils" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: true, streaming: false },
    agentScores: { jsonOutput: 1, nonInteractive: 3, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 3 },
    agentScore: 6,
    categories: ["files", "rename", "editor"],
    tier: "community",
    description: "Edit directory in $EDITOR."
  },
  {
    slug: "sponge",
    name: "sponge",
    vendor: { name: "moreutils", domain: "joeyh.name/code/moreutils", verified: false },
    repo: "https://github.com/treeform/sponge",
    docs: "https://linux.die.net/man/1/sponge",
    install: { brew: "moreutils", apt: "moreutils" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["files", "pipeline"],
    tier: "community",
    description: "Soak up stdin and write to a file - safe in-place editing."
  },
  {
    slug: "ts",
    name: "ts",
    vendor: { name: "moreutils", domain: "joeyh.name/code/moreutils", verified: false },
    repo: "https://github.com/moreutils/moreutils",
    docs: "https://linux.die.net/man/1/ts",
    install: { brew: "moreutils", apt: "moreutils" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["logging", "timestamp"],
    tier: "community",
    description: "Timestamp standard input."
  },
  {
    slug: "chronic",
    name: "chronic",
    vendor: { name: "moreutils", domain: "joeyh.name/code/moreutils", verified: false },
    repo: "https://github.com/moreutils/moreutils",
    docs: "https://linux.die.net/man/1/chronic",
    install: { brew: "moreutils", apt: "moreutils" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["cron", "output"],
    tier: "community",
    description: "Runs a command quietly unless it fails."
  },
  {
    slug: "ifne",
    name: "ifne",
    vendor: { name: "moreutils", domain: "joeyh.name/code/moreutils", verified: false },
    repo: "https://github.com/moreutils/moreutils",
    docs: "https://linux.die.net/man/1/ifne",
    install: { brew: "moreutils", apt: "moreutils" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["conditional", "pipeline"],
    tier: "community",
    description: "Run a command if standard input is not empty."
  },
  // Security/Pentest tools
  {
    slug: "nuclei",
    name: "Nuclei",
    vendor: { name: "ProjectDiscovery", domain: "projectdiscovery.io", verified: false },
    repo: "https://github.com/projectdiscovery/nuclei",
    docs: "https://docs.projectdiscovery.io/tools/nuclei/overview",
    install: { brew: "nuclei", go: "github.com/projectdiscovery/nuclei/v3/cmd/nuclei" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["security", "scanning", "vulnerability"],
    tier: "community",
    description: "Fast and customizable vulnerability scanner based on templates."
  },
  {
    slug: "httpx",
    name: "httpx",
    vendor: { name: "ProjectDiscovery", domain: "projectdiscovery.io", verified: false },
    repo: "https://github.com/projectdiscovery/httpx",
    docs: "https://github.com/projectdiscovery/httpx#readme",
    install: { go: "github.com/projectdiscovery/httpx/cmd/httpx" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["http", "recon", "security"],
    tier: "community",
    description: "Fast HTTP probing tool and toolkit."
  },
  {
    slug: "subfinder",
    name: "Subfinder",
    vendor: { name: "ProjectDiscovery", domain: "projectdiscovery.io", verified: false },
    repo: "https://github.com/projectdiscovery/subfinder",
    docs: "https://github.com/projectdiscovery/subfinder#readme",
    install: { go: "github.com/projectdiscovery/subfinder/v2/cmd/subfinder" },
    capabilities: { jsonOutput: true, auth: ["API keys"], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["dns", "recon", "security"],
    tier: "community",
    description: "Fast passive subdomain enumeration tool."
  },
  {
    slug: "naabu",
    name: "Naabu",
    vendor: { name: "ProjectDiscovery", domain: "projectdiscovery.io", verified: false },
    repo: "https://github.com/projectdiscovery/naabu",
    docs: "https://github.com/projectdiscovery/naabu#readme",
    install: { go: "github.com/projectdiscovery/naabu/v2/cmd/naabu" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["port-scanner", "recon", "security"],
    tier: "community",
    description: "Fast port scanner with SYN/CONNECT scanning."
  },
  // Image optimization
  {
    slug: "pngquant",
    name: "pngquant",
    vendor: { name: "Kornel Lesiński", domain: "pngquant.org", verified: false },
    repo: "https://github.com/kornelski/pngquant",
    docs: "https://pngquant.org/",
    install: { brew: "pngquant", apt: "pngquant" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["images", "optimization", "png"],
    tier: "community",
    description: "PNG image compression utility using quantization."
  },
  {
    slug: "jpegoptim",
    name: "jpegoptim",
    vendor: { name: "Timo Kokkonen", domain: "github.com/tjko", verified: false },
    repo: "https://github.com/tjko/jpegoptim",
    docs: "https://github.com/tjko/jpegoptim#readme",
    install: { brew: "jpegoptim", apt: "jpegoptim" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["images", "optimization", "jpeg"],
    tier: "community",
    description: "Utility to optimize JPEG files."
  },
  {
    slug: "optipng",
    name: "OptiPNG",
    vendor: { name: "Cosmin Truta", domain: "optipng.sourceforge.net", verified: false },
    repo: "https://github.com/nickyout/optipng",
    docs: "http://optipng.sourceforge.net/",
    install: { brew: "optipng", apt: "optipng" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["images", "optimization", "png"],
    tier: "community",
    description: "PNG optimizer that recompresses image files."
  },
  {
    slug: "svgo",
    name: "SVGO",
    vendor: { name: "svg", domain: "github.com/svg", verified: false },
    repo: "https://github.com/svg/svgo",
    docs: "https://github.com/svg/svgo#readme",
    install: { npm: "svgo" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["images", "optimization", "svg"],
    tier: "community",
    description: "Node.js tool for optimizing SVG files."
  },
  // Templating
  {
    slug: "envsubst",
    name: "envsubst",
    vendor: { name: "GNU", domain: "gnu.org", verified: true },
    repo: "https://github.com/a8m/envsubst",
    docs: "https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html",
    install: { brew: "gettext", apt: "gettext-base" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["template", "environment"],
    tier: "verified",
    description: "Substitute environment variables in shell format strings."
  },
  {
    slug: "gomplate",
    name: "Gomplate",
    vendor: { name: "hairyhenderson", domain: "gomplate.ca", verified: false },
    repo: "https://github.com/hairyhenderson/gomplate",
    docs: "https://docs.gomplate.ca/",
    install: { brew: "gomplate", go: "github.com/hairyhenderson/gomplate/v4/cmd/gomplate" },
    capabilities: { jsonOutput: true, auth: ["various data sources"], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["template", "devops"],
    tier: "community",
    description: "Flexible Go template processor with data source support."
  },
  {
    slug: "j2cli",
    name: "j2cli",
    vendor: { name: "kolypto", domain: "github.com/kolypto", verified: false },
    repo: "https://github.com/kolypto/j2cli",
    docs: "https://github.com/kolypto/j2cli#readme",
    install: { pip: "j2cli" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["template", "jinja2"],
    tier: "community",
    description: "Jinja2 command-line interface."
  }
];

// Filter out existing tools
const toolsToAdd = newTools.filter(t => !existingSlugs.has(t.slug));

console.log(`Adding ${toolsToAdd.length} new tools (${newTools.length - toolsToAdd.length} skipped as duplicates)`);

// Add new tools
data.tools.push(...toolsToAdd);

// Update timestamp
data.updated = new Date().toISOString().split('T')[0];

// Write back
fs.writeFileSync(toolsPath, JSON.stringify(data, null, 2));

console.log(`Total tools now: ${data.tools.length}`);
console.log('Added tools:', toolsToAdd.map(t => t.slug).join(', '));
