#!/usr/bin/env node
// Batch 5: Add 60 more CLI tools to reach 700+

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const toolsPath = path.join(__dirname, '../registry/tools.json');
const data = JSON.parse(fs.readFileSync(toolsPath, 'utf8'));

const existingSlugs = new Set(data.tools.map(t => t.slug));

const newTools = [
  // More Rust tools
  {
    slug: "wezterm",
    name: "WezTerm",
    vendor: { name: "Wez Furlong", domain: "wezfurlong.org", verified: false },
    repo: "https://github.com/wez/wezterm",
    docs: "https://wezfurlong.org/wezterm/",
    install: { brew: "wezterm" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 1, tokenEfficiency: 2, safetyFeatures: 4, pipelineFriendly: 1 },
    agentScore: 3,
    categories: ["terminal", "emulator"],
    tier: "community",
    description: "GPU-accelerated cross-platform terminal emulator and multiplexer."
  },
  {
    slug: "atuin",
    name: "Atuin",
    vendor: { name: "Atuin", domain: "atuin.sh", verified: false },
    repo: "https://github.com/atuinsh/atuin",
    docs: "https://docs.atuin.sh/",
    install: { brew: "atuin", cargo: "atuin" },
    capabilities: { jsonOutput: true, auth: ["atuin account"], idempotent: true, interactive: true, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 3, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["shell", "history", "sync"],
    tier: "community",
    description: "Magical shell history with sync, search, and backup."
  },
  {
    slug: "ouch",
    name: "ouch",
    vendor: { name: "ouch-org", domain: "github.com/ouch-org", verified: false },
    repo: "https://github.com/ouch-org/ouch",
    docs: "https://github.com/ouch-org/ouch#readme",
    install: { brew: "ouch", cargo: "ouch" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["compression", "archive"],
    tier: "community",
    description: "Painless compression and decompression in the terminal."
  },
  {
    slug: "tealdeer",
    name: "tealdeer",
    vendor: { name: "dbrgn", domain: "github.com/dbrgn", verified: false },
    repo: "https://github.com/dbrgn/tealdeer",
    docs: "https://dbrgn.github.io/tealdeer/",
    install: { brew: "tealdeer", cargo: "tealdeer" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 4 },
    agentScore: 9,
    categories: ["documentation", "tldr", "help"],
    tier: "community",
    description: "Very fast implementation of tldr in Rust."
  },
  {
    slug: "gitoxide",
    name: "gitoxide",
    vendor: { name: "Byron", domain: "github.com/Byron", verified: false },
    repo: "https://github.com/Byron/gitoxide",
    docs: "https://github.com/Byron/gitoxide#readme",
    install: { brew: "gitoxide", cargo: "gitoxide" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["git", "vcs"],
    tier: "community",
    description: "Idiomatic, lean, fast & safe pure Rust implementation of Git."
  },
  {
    slug: "jless",
    name: "jless",
    vendor: { name: "Paul Julius", domain: "jless.io", verified: false },
    repo: "https://github.com/PaulJuliusMartinez/jless",
    docs: "https://jless.io/",
    install: { brew: "jless", cargo: "jless" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: true, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 3, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 3 },
    agentScore: 7,
    categories: ["json", "viewer", "tui"],
    tier: "community",
    description: "Command-line JSON viewer with vim-like navigation."
  },
  {
    slug: "hurl",
    name: "Hurl",
    vendor: { name: "Orange", domain: "hurl.dev", verified: true },
    repo: "https://github.com/Orange-OpenSource/hurl",
    docs: "https://hurl.dev/docs/",
    install: { brew: "hurl", cargo: "hurl" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["http", "testing", "api"],
    tier: "verified",
    description: "Run and test HTTP requests with plain text file format."
  },
  {
    slug: "difftastic",
    name: "Difftastic",
    vendor: { name: "Wilfred Hughes", domain: "difftastic.wilfred.me.uk", verified: false },
    repo: "https://github.com/Wilfred/difftastic",
    docs: "https://difftastic.wilfred.me.uk/",
    install: { brew: "difftastic", cargo: "difftastic" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["diff", "git", "devtools"],
    tier: "community",
    description: "Structural diff tool that understands syntax."
  },
  {
    slug: "miniserve",
    name: "miniserve",
    vendor: { name: "svenstaro", domain: "github.com/svenstaro", verified: false },
    repo: "https://github.com/svenstaro/miniserve",
    docs: "https://github.com/svenstaro/miniserve#readme",
    install: { brew: "miniserve", cargo: "miniserve" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["http", "server", "file-sharing"],
    tier: "community",
    description: "CLI tool to serve files and directories over HTTP."
  },
  {
    slug: "rustscan",
    name: "RustScan",
    vendor: { name: "RustScan", domain: "github.com/RustScan", verified: false },
    repo: "https://github.com/RustScan/RustScan",
    docs: "https://rustscan.github.io/RustScan/",
    install: { brew: "rustscan", cargo: "rustscan" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 3, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["security", "networking", "scanning"],
    tier: "community",
    description: "Modern port scanner - fast alternative to Nmap."
  },
  {
    slug: "zola",
    name: "Zola",
    vendor: { name: "getzola", domain: "getzola.org", verified: false },
    repo: "https://github.com/getzola/zola",
    docs: "https://www.getzola.org/documentation/",
    install: { brew: "zola", cargo: "zola" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["static-site", "documentation"],
    tier: "community",
    description: "Fast static site generator in a single binary with everything built-in."
  },
  // More Go tools
  {
    slug: "lazygit",
    name: "lazygit",
    vendor: { name: "Jesse Duffield", domain: "github.com/jesseduffield", verified: false },
    repo: "https://github.com/jesseduffield/lazygit",
    docs: "https://github.com/jesseduffield/lazygit#readme",
    install: { brew: "lazygit", go: "github.com/jesseduffield/lazygit" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: true, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 2, tokenEfficiency: 3, safetyFeatures: 4, pipelineFriendly: 2 },
    agentScore: 5,
    categories: ["git", "tui"],
    tier: "community",
    description: "Simple terminal UI for git commands."
  },
  {
    slug: "lazydocker",
    name: "lazydocker",
    vendor: { name: "Jesse Duffield", domain: "github.com/jesseduffield", verified: false },
    repo: "https://github.com/jesseduffield/lazydocker",
    docs: "https://github.com/jesseduffield/lazydocker#readme",
    install: { brew: "lazydocker", go: "github.com/jesseduffield/lazydocker" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 2, tokenEfficiency: 3, safetyFeatures: 4, pipelineFriendly: 2 },
    agentScore: 5,
    categories: ["docker", "containers", "tui"],
    tier: "community",
    description: "Simple terminal UI for docker and docker-compose."
  },
  {
    slug: "k9s",
    name: "k9s",
    vendor: { name: "derailed", domain: "k9scli.io", verified: false },
    repo: "https://github.com/derailed/k9s",
    docs: "https://k9scli.io/",
    install: { brew: "k9s" },
    capabilities: { jsonOutput: false, auth: ["kubeconfig"], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 2, tokenEfficiency: 3, safetyFeatures: 4, pipelineFriendly: 2 },
    agentScore: 5,
    categories: ["kubernetes", "tui"],
    tier: "community",
    description: "Kubernetes CLI to manage clusters with a terminal UI."
  },
  {
    slug: "peco",
    name: "peco",
    vendor: { name: "peco", domain: "github.com/peco", verified: false },
    repo: "https://github.com/peco/peco",
    docs: "https://github.com/peco/peco#readme",
    install: { brew: "peco", go: "github.com/peco/peco/cmd/peco" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 2, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 6,
    categories: ["search", "filter", "interactive"],
    tier: "community",
    description: "Simplistic interactive filtering tool."
  },
  {
    slug: "ghq",
    name: "ghq",
    vendor: { name: "x-motemen", domain: "github.com/x-motemen", verified: false },
    repo: "https://github.com/x-motemen/ghq",
    docs: "https://github.com/x-motemen/ghq#readme",
    install: { brew: "ghq", go: "github.com/x-motemen/ghq" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["git", "repository-management"],
    tier: "community",
    description: "Manage remote repository clones with local directory structure."
  },
  {
    slug: "glow",
    name: "Glow",
    vendor: { name: "Charm", domain: "charm.sh", verified: false },
    repo: "https://github.com/charmbracelet/glow",
    docs: "https://github.com/charmbracelet/glow#readme",
    install: { brew: "glow", go: "github.com/charmbracelet/glow" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: true, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 4, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["markdown", "viewer", "tui"],
    tier: "community",
    description: "Render markdown on the CLI with glamour."
  },
  {
    slug: "charm",
    name: "Charm",
    vendor: { name: "Charm", domain: "charm.sh", verified: false },
    repo: "https://github.com/charmbracelet/charm",
    docs: "https://charm.sh/",
    install: { brew: "charm", go: "github.com/charmbracelet/charm" },
    capabilities: { jsonOutput: true, auth: ["charm account"], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["cloud", "sync", "devtools"],
    tier: "community",
    description: "The Charm Cloud - sync, encrypt, and share your data."
  },
  {
    slug: "soft-serve",
    name: "Soft Serve",
    vendor: { name: "Charm", domain: "charm.sh", verified: false },
    repo: "https://github.com/charmbracelet/soft-serve",
    docs: "https://github.com/charmbracelet/soft-serve#readme",
    install: { brew: "soft-serve", go: "github.com/charmbracelet/soft-serve/cmd/soft" },
    capabilities: { jsonOutput: false, auth: ["ssh keys"], idempotent: true, interactive: true, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 4, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["git", "server"],
    tier: "community",
    description: "Self-hostable Git server with a TUI and SSH access."
  },
  {
    slug: "vhs",
    name: "VHS",
    vendor: { name: "Charm", domain: "charm.sh", verified: false },
    repo: "https://github.com/charmbracelet/vhs",
    docs: "https://github.com/charmbracelet/vhs#readme",
    install: { brew: "vhs", go: "github.com/charmbracelet/vhs" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["recording", "terminal", "gif"],
    tier: "community",
    description: "Write terminal GIFs as code for generating terminal recordings."
  },
  {
    slug: "mods",
    name: "Mods",
    vendor: { name: "Charm", domain: "charm.sh", verified: false },
    repo: "https://github.com/charmbracelet/mods",
    docs: "https://github.com/charmbracelet/mods#readme",
    install: { brew: "mods", go: "github.com/charmbracelet/mods" },
    capabilities: { jsonOutput: true, auth: ["various LLM APIs"], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["ai", "llm", "devtools"],
    tier: "community",
    description: "AI on the command line - pipe to LLMs for instant answers."
  },
  // AWS/Cloud specific tools
  {
    slug: "eksctl",
    name: "eksctl",
    vendor: { name: "Weaveworks", domain: "eksctl.io", verified: true },
    repo: "https://github.com/eksctl-io/eksctl",
    docs: "https://eksctl.io/",
    install: { brew: "eksctl" },
    capabilities: { jsonOutput: true, auth: ["AWS credentials"], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["aws", "kubernetes", "eks"],
    tier: "verified",
    description: "Official CLI for Amazon EKS - creating and managing clusters."
  },
  {
    slug: "copilot-cli",
    name: "AWS Copilot",
    vendor: { name: "Amazon Web Services", domain: "aws.amazon.com", verified: true },
    repo: "https://github.com/aws/copilot-cli",
    docs: "https://aws.github.io/copilot-cli/",
    install: { brew: "aws/tap/copilot-cli" },
    capabilities: { jsonOutput: true, auth: ["AWS credentials"], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 4, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 9,
    categories: ["aws", "containers", "deployment"],
    tier: "verified",
    description: "CLI for launching and managing containerized apps on AWS."
  },
  {
    slug: "sam",
    name: "AWS SAM CLI",
    vendor: { name: "Amazon Web Services", domain: "aws.amazon.com", verified: true },
    repo: "https://github.com/aws/aws-sam-cli",
    docs: "https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-command-reference.html",
    install: { brew: "aws-sam-cli", pip: "aws-sam-cli" },
    capabilities: { jsonOutput: true, auth: ["AWS credentials"], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 4, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 9,
    categories: ["aws", "serverless", "lambda"],
    tier: "verified",
    description: "CLI tool for building and testing AWS Lambda applications."
  },
  {
    slug: "amplify",
    name: "AWS Amplify CLI",
    vendor: { name: "Amazon Web Services", domain: "aws.amazon.com", verified: true },
    repo: "https://github.com/aws-amplify/amplify-cli",
    docs: "https://docs.amplify.aws/cli/",
    install: { npm: "@aws-amplify/cli" },
    capabilities: { jsonOutput: true, auth: ["AWS credentials"], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 3, tokenEfficiency: 3, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["aws", "fullstack", "backend"],
    tier: "verified",
    description: "CLI for creating, managing, and deploying AWS Amplify apps."
  },
  // More specialized tools
  {
    slug: "fq",
    name: "fq",
    vendor: { name: "Mattias Wadman", domain: "github.com/wader", verified: false },
    repo: "https://github.com/wader/fq",
    docs: "https://github.com/wader/fq#readme",
    install: { brew: "fq", go: "github.com/wader/fq" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 4, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 4 },
    agentScore: 9,
    categories: ["binary", "data", "forensics"],
    tier: "community",
    description: "jq for binary formats - query and transform binary data."
  },
  {
    slug: "pv",
    name: "pv",
    vendor: { name: "Andrew Wood", domain: "ivarch.com/programs/pv", verified: false },
    repo: "https://github.com/a-j-wood/pv",
    docs: "https://www.ivarch.com/programs/pv.shtml",
    install: { brew: "pv", apt: "pv" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["pipe", "progress", "monitoring"],
    tier: "community",
    description: "Pipe Viewer - monitor the progress of data through a pipeline."
  },
  {
    slug: "parallel",
    name: "GNU Parallel",
    vendor: { name: "GNU", domain: "gnu.org/software/parallel", verified: true },
    repo: "https://github.com/martinda/gnu-parallel",
    docs: "https://www.gnu.org/software/parallel/parallel_tutorial.html",
    install: { brew: "parallel", apt: "parallel" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["parallel", "shell", "automation"],
    tier: "verified",
    description: "Build and execute shell command lines in parallel."
  },
  {
    slug: "xargs",
    name: "xargs",
    vendor: { name: "GNU", domain: "gnu.org", verified: true },
    repo: "https://github.com/util-linux/util-linux",
    docs: "https://man7.org/linux/man-pages/man1/xargs.1.html",
    install: { apt: "findutils" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 1, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["shell", "pipeline"],
    tier: "verified",
    description: "Build and execute command lines from standard input."
  },
  {
    slug: "gron",
    name: "gron",
    vendor: { name: "Tom Hudson", domain: "github.com/tomnomnom", verified: false },
    repo: "https://github.com/tomnomnom/gron",
    docs: "https://github.com/tomnomnom/gron#readme",
    install: { brew: "gron", go: "github.com/tomnomnom/gron" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["json", "grep", "devtools"],
    tier: "community",
    description: "Make JSON greppable by transforming it to discrete assignments."
  },
  {
    slug: "jc",
    name: "jc",
    vendor: { name: "Kelly Brazil", domain: "github.com/kellyjonbrazil", verified: false },
    repo: "https://github.com/kellyjonbrazil/jc",
    docs: "https://kellyjonbrazil.github.io/jc/",
    install: { brew: "jc", pip: "jc" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["json", "parsing", "devtools"],
    tier: "community",
    description: "CLI tool that converts output of popular commands to JSON."
  },
  {
    slug: "jo",
    name: "jo",
    vendor: { name: "Jan-Piet Mens", domain: "github.com/jpmens", verified: false },
    repo: "https://github.com/jpmens/jo",
    docs: "https://github.com/jpmens/jo#readme",
    install: { brew: "jo", apt: "jo" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["json", "generation", "devtools"],
    tier: "community",
    description: "Small utility to create JSON objects from command line arguments."
  },
  {
    slug: "hostctl",
    name: "hostctl",
    vendor: { name: "guumaster", domain: "guumaster.github.io/hostctl", verified: false },
    repo: "https://github.com/guumaster/hostctl",
    docs: "https://guumaster.github.io/hostctl/",
    install: { brew: "hostctl" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["networking", "hosts", "devtools"],
    tier: "community",
    description: "Manage /etc/hosts like a pro with profiles and automation."
  },
  {
    slug: "tldr",
    name: "tldr",
    vendor: { name: "tldr-pages", domain: "tldr.sh", verified: false },
    repo: "https://github.com/tldr-pages/tldr",
    docs: "https://tldr.sh/",
    install: { brew: "tldr", npm: "tldr" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 4 },
    agentScore: 9,
    categories: ["documentation", "help"],
    tier: "community",
    description: "Simplified and community-driven man pages."
  },
  {
    slug: "cheat",
    name: "cheat",
    vendor: { name: "Chris Allen Lane", domain: "github.com/cheat", verified: false },
    repo: "https://github.com/cheat/cheat",
    docs: "https://github.com/cheat/cheat#readme",
    install: { brew: "cheat", go: "github.com/cheat/cheat/cmd/cheat" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 4 },
    agentScore: 9,
    categories: ["documentation", "cheatsheets"],
    tier: "community",
    description: "Create and view interactive cheatsheets on the command-line."
  },
  {
    slug: "navi",
    name: "navi",
    vendor: { name: "Denis Isidoro", domain: "github.com/denisidoro", verified: false },
    repo: "https://github.com/denisidoro/navi",
    docs: "https://github.com/denisidoro/navi#readme",
    install: { brew: "navi", cargo: "navi" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: true, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 3, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 3 },
    agentScore: 7,
    categories: ["cheatsheets", "interactive"],
    tier: "community",
    description: "Interactive cheatsheet tool for the command line."
  },
  // Messaging/Communication
  {
    slug: "slack-cli",
    name: "Slack CLI",
    vendor: { name: "Slack", domain: "slack.dev", verified: true },
    repo: "https://github.com/slackapi/slack-cli",
    docs: "https://api.slack.com/automation/cli",
    install: {},
    capabilities: { jsonOutput: true, auth: ["slack auth"], idempotent: true, interactive: true, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 4, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 9,
    categories: ["slack", "messaging", "automation"],
    tier: "verified",
    description: "Official Slack CLI for building and deploying Slack apps."
  },
  {
    slug: "telegram-cli",
    name: "telegram-cli",
    vendor: { name: "vysheng", domain: "github.com/vysheng", verified: false },
    repo: "https://github.com/vysheng/tg",
    docs: "https://github.com/vysheng/tg#readme",
    install: {},
    capabilities: { jsonOutput: false, auth: ["phone number"], idempotent: false, interactive: true, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 3, tokenEfficiency: 3, safetyFeatures: 3, pipelineFriendly: 3 },
    agentScore: 6,
    categories: ["telegram", "messaging"],
    tier: "community",
    description: "Command line interface for Telegram messenger."
  },
  // Markdown/Text tools
  {
    slug: "pandoc",
    name: "Pandoc",
    vendor: { name: "John MacFarlane", domain: "pandoc.org", verified: true },
    repo: "https://github.com/jgm/pandoc",
    docs: "https://pandoc.org/MANUAL.html",
    install: { brew: "pandoc", apt: "pandoc" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["conversion", "markdown", "documents"],
    tier: "verified",
    description: "Universal document converter - convert between markup formats."
  },
  {
    slug: "asciidoctor",
    name: "Asciidoctor",
    vendor: { name: "Asciidoctor", domain: "asciidoctor.org", verified: false },
    repo: "https://github.com/asciidoctor/asciidoctor",
    docs: "https://docs.asciidoctor.org/",
    install: { brew: "asciidoctor", gem: "asciidoctor" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["asciidoc", "documentation", "conversion"],
    tier: "community",
    description: "Fast, open source text processor for writing documentation."
  },
  {
    slug: "vale",
    name: "Vale",
    vendor: { name: "errata-ai", domain: "vale.sh", verified: false },
    repo: "https://github.com/errata-ai/vale",
    docs: "https://vale.sh/docs/",
    install: { brew: "vale" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["prose", "linting", "writing"],
    tier: "community",
    description: "Syntax-aware linter for prose built with speed and extensibility."
  },
  // Process/Performance tools
  {
    slug: "perf",
    name: "perf",
    vendor: { name: "Linux Kernel", domain: "perf.wiki.kernel.org", verified: true },
    repo: "https://github.com/torvalds/linux",
    docs: "https://perf.wiki.kernel.org/index.php/Main_Page",
    install: { apt: "linux-tools-common" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 3, nonInteractive: 5, tokenEfficiency: 3, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 8,
    categories: ["performance", "profiling", "linux"],
    tier: "verified",
    description: "Linux profiling with performance counters."
  },
  {
    slug: "flamegraph",
    name: "FlameGraph",
    vendor: { name: "Brendan Gregg", domain: "brendangregg.com", verified: false },
    repo: "https://github.com/brendangregg/FlameGraph",
    docs: "https://www.brendangregg.com/flamegraphs.html",
    install: {},
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["performance", "profiling", "visualization"],
    tier: "community",
    description: "Stack trace visualizer for performance profiling."
  },
  {
    slug: "sampler",
    name: "Sampler",
    vendor: { name: "sqshq", domain: "sampler.dev", verified: false },
    repo: "https://github.com/sqshq/sampler",
    docs: "https://sampler.dev/",
    install: { brew: "sampler" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 3, tokenEfficiency: 3, safetyFeatures: 4, pipelineFriendly: 3 },
    agentScore: 6,
    categories: ["monitoring", "dashboard", "tui"],
    tier: "community",
    description: "Tool for shell commands execution, visualization and alerting."
  },
  // More AI/ML tools
  {
    slug: "ollama",
    name: "Ollama",
    vendor: { name: "Ollama", domain: "ollama.com", verified: true },
    repo: "https://github.com/ollama/ollama",
    docs: "https://ollama.com/library",
    install: { brew: "ollama" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: true, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 4, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 4 },
    agentScore: 9,
    categories: ["ai", "llm", "local"],
    tier: "verified",
    description: "Get up and running with large language models locally."
  },
  {
    slug: "llm",
    name: "llm",
    vendor: { name: "Simon Willison", domain: "llm.datasette.io", verified: false },
    repo: "https://github.com/simonw/llm",
    docs: "https://llm.datasette.io/",
    install: { brew: "llm", pip: "llm" },
    capabilities: { jsonOutput: true, auth: ["API keys"], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["ai", "llm", "devtools"],
    tier: "community",
    description: "CLI tool and Python library for interacting with LLMs."
  },
  {
    slug: "aider",
    name: "aider",
    vendor: { name: "Paul Gauthier", domain: "aider.chat", verified: false },
    repo: "https://github.com/paul-gauthier/aider",
    docs: "https://aider.chat/docs/",
    install: { pip: "aider-chat" },
    capabilities: { jsonOutput: false, auth: ["API keys"], idempotent: false, interactive: true, streaming: true },
    agentScores: { jsonOutput: 2, nonInteractive: 3, tokenEfficiency: 3, safetyFeatures: 4, pipelineFriendly: 3 },
    agentScore: 6,
    categories: ["ai", "coding", "assistant"],
    tier: "community",
    description: "AI pair programming in your terminal."
  },
  {
    slug: "fabric",
    name: "Fabric",
    vendor: { name: "Daniel Miessler", domain: "github.com/danielmiessler", verified: false },
    repo: "https://github.com/danielmiessler/fabric",
    docs: "https://github.com/danielmiessler/fabric#readme",
    install: { pip: "fabric-ai" },
    capabilities: { jsonOutput: true, auth: ["API keys"], idempotent: true, interactive: false, streaming: true },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 4, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["ai", "prompts", "automation"],
    tier: "community",
    description: "Open-source framework for augmenting humans using AI."
  },
  // VPN/Network security
  {
    slug: "wireguard",
    name: "WireGuard",
    vendor: { name: "WireGuard", domain: "wireguard.com", verified: true },
    repo: "https://github.com/WireGuard/wireguard-tools",
    docs: "https://www.wireguard.com/quickstart/",
    install: { brew: "wireguard-tools", apt: "wireguard-tools" },
    capabilities: { jsonOutput: false, auth: ["config files"], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 4 },
    agentScore: 9,
    categories: ["vpn", "networking", "security"],
    tier: "verified",
    description: "Fast, modern, secure VPN tunnel utilities."
  },
  {
    slug: "tailscale",
    name: "Tailscale",
    vendor: { name: "Tailscale", domain: "tailscale.com", verified: true },
    repo: "https://github.com/tailscale/tailscale",
    docs: "https://tailscale.com/kb/",
    install: { brew: "tailscale" },
    capabilities: { jsonOutput: true, auth: ["tailscale auth"], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["vpn", "networking", "mesh"],
    tier: "verified",
    description: "Zero config VPN that works on any platform."
  },
  // Config/IaC Linting
  {
    slug: "yamllint",
    name: "yamllint",
    vendor: { name: "Adrien Vergé", domain: "github.com/adrienverge", verified: false },
    repo: "https://github.com/adrienverge/yamllint",
    docs: "https://yamllint.readthedocs.io/",
    install: { brew: "yamllint", pip: "yamllint" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["yaml", "linting"],
    tier: "community",
    description: "Linter for YAML files."
  },
  {
    slug: "jsonlint",
    name: "jsonlint",
    vendor: { name: "zaach", domain: "github.com/zaach", verified: false },
    repo: "https://github.com/zaach/jsonlint",
    docs: "https://github.com/zaach/jsonlint#readme",
    install: { npm: "jsonlint" },
    capabilities: { jsonOutput: false, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 2, nonInteractive: 5, tokenEfficiency: 5, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 9,
    categories: ["json", "linting"],
    tier: "community",
    description: "JSON syntax validator and reformatter."
  },
  {
    slug: "tflint",
    name: "TFLint",
    vendor: { name: "terraform-linters", domain: "github.com/terraform-linters", verified: false },
    repo: "https://github.com/terraform-linters/tflint",
    docs: "https://github.com/terraform-linters/tflint#readme",
    install: { brew: "tflint" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["terraform", "linting"],
    tier: "community",
    description: "Terraform linter focused on possible errors and best practices."
  },
  {
    slug: "checkov",
    name: "Checkov",
    vendor: { name: "Bridgecrew", domain: "checkov.io", verified: true },
    repo: "https://github.com/bridgecrewio/checkov",
    docs: "https://www.checkov.io/",
    install: { brew: "checkov", pip: "checkov" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["iac", "security", "compliance"],
    tier: "verified",
    description: "Static analysis for infrastructure as code."
  },
  {
    slug: "kics",
    name: "KICS",
    vendor: { name: "Checkmarx", domain: "kics.io", verified: true },
    repo: "https://github.com/Checkmarx/kics",
    docs: "https://docs.kics.io/",
    install: { brew: "kics" },
    capabilities: { jsonOutput: true, auth: [], idempotent: true, interactive: false, streaming: false },
    agentScores: { jsonOutput: 5, nonInteractive: 5, tokenEfficiency: 4, safetyFeatures: 5, pipelineFriendly: 5 },
    agentScore: 10,
    categories: ["iac", "security", "scanning"],
    tier: "verified",
    description: "Find security vulnerabilities and compliance issues in IaC."
  }
];

// Filter out existing tools
const toolsToAdd = newTools.filter(t => !existingSlugs.has(t.slug));

console.log(`Adding ${toolsToAdd.length} new tools (${newTools.length - toolsToAdd.length} skipped as duplicates)`);

// Add new tools
data.tools.push(...toolsToAdd);

// Update timestamp
data.updated = new Date().toISOString().split('T')[0];

// Write back
fs.writeFileSync(toolsPath, JSON.stringify(data, null, 2));

console.log(`Total tools now: ${data.tools.length}`);
console.log('Added tools:', toolsToAdd.map(t => t.slug).join(', '));
