/**
 * Changelog from GitHub Releases.
 * Zero maintenance — auto-generated by release workflow.
 */

const RELEASES_URL = 'https://api.github.com/repos/askeluv/mcli/releases';

export interface Release {
  tag_name: string;
  name: string;
  published_at: string;
  body: string;
  html_url: string;
}

export interface ChangelogEntry {
  version: string;
  date: string;
  notes: string;
  url: string;
}

export async function fetchReleases(limit: number = 10): Promise<Release[]> {
  const response = await fetch(`${RELEASES_URL}?per_page=${limit}`, {
    headers: { 'User-Agent': 'mcli' },
  });
  
  if (!response.ok) {
    throw new Error(`Failed to fetch releases: ${response.status}`);
  }
  
  return response.json() as Promise<Release[]>;
}

export function formatRelease(release: Release): ChangelogEntry {
  return {
    version: release.tag_name.replace(/^v/, ''),
    date: release.published_at.split('T')[0],
    notes: release.body || 'No release notes.',
    url: release.html_url,
  };
}

export function formatChangelogText(entries: ChangelogEntry[], verbose: boolean = false): string {
  const lines: string[] = [];
  
  for (const entry of entries) {
    lines.push(`## ${entry.version} (${entry.date})`);
    if (verbose) {
      lines.push('');
      lines.push(entry.notes);
      lines.push('');
      lines.push(`→ ${entry.url}`);
    } else {
      // Compact: first line of notes only
      const firstLine = entry.notes.split('\n').find(l => l.trim()) || 'No release notes.';
      lines.push(`  ${firstLine.slice(0, 80)}${firstLine.length > 80 ? '...' : ''}`);
    }
    lines.push('');
  }
  
  return lines.join('\n');
}

export function formatChangelogJson(entries: ChangelogEntry[]): string {
  return JSON.stringify(entries, null, 2);
}
